CREATE TABLE Foods
(
	FoodID INT IDENTITY NOT NULL PRIMARY KEY,
	Name VARCHAR(50) NOT NULL,
	Calories INT,
	Fat FLOAT,
	Carbs FLOAT,
	Protein FLOAT
)
CREATE TABLE Meals 
(
	MealID INT IDENTITY NOT NULL PRIMARY KEY, 
	MealType CHAR(1) NOT NULL,
	MealDate DATE NOT NULL,
	CONSTRAINT AK_UniqueMeal UNIQUE (MealType, MealDate)
)
CREATE TABLE MealContents
(
	MealID INT NOT NULL,
	FoodID INT NOT NULL,
	Servings FLOAT NOT NULL,
	PRIMARY KEY (MealID, FoodID),
	FOREIGN KEY (MealID)
		REFERENCES Meals (MealID),
	FOREIGN KEY (FoodID)
		REFERENCES Foods (FoodID)
)